# Estágio 1: Build
FROM maven:3.9.9-eclipse-temurin-24 AS build
LABEL authors="nobru"
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Estágio 2: Execução
FROM eclipse-temurin:24-jre
WORKDIR /app

# Copia o JAR do estágio de build de forma dinâmica
COPY --from=build /app/target/*.jar app.jar

ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
ENV TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
ENV TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]