spring.application.name=api-ai
spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.vertex.ai.gemini.project-id=${GCP_PROJECT_ID}
#spring.ai.vertex.ai.gemini.location=${GCP_LOCATION}

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:schema-postgresql.sql
spring.jpa.defer-datasource-initialization=true

# Database Postgres configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect